### PR TITLE
Remove all references to my username

### PR DESCRIPTION
**Pull request by aryann**
Note that this pull request is dependent on https://github.com/googleapis/google-cloud-cpp-bigquery/pull/2.

I understand GitHub doesn't have great support for dependent pull requests. Let me know if this is okay as-is, or if you prefer that I send out larger pull requests, or if there is another, better way to handle dependent changes.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-bigquery/4)

### CODE REVIEW

**Comment by coryan** [comment]
Unfortunately the workflow that seems best is to create multiple (dependent) branches in your workspace, and then send PRs for each one.  Something like:

```sh
git checkout -b my-change-pr1
# make some edits, create a PR from this branch
git checkout -b my-change-pr2
# make some edits, ... wait until the first PR is merged then
git rebase master
# and send a second PR
```

**Comment by aryann** [comment]
> FWIW, the changes in the last two commits LGTM. Happy to approve once #2 is merged and you rebase this PR.

Okay cool. So I'll just keep doing what I've been doing. I've rebased this now that my previous PR is merged.

**Comment by aryann** [comment]
> I thought you were going to clean the user agent string in this PR too? Do you want to do that later?
> 

Done. I wished there was a way to atomically reply to multiple comments on GitHub!

> > Reviewed 3 of 18 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-bigquery/4#-:-LrB4Zs7C5BEUqGgmdJl:b-r27cxj)_ status: :shipit: complete! all files reviewed, all discussions resolved
> 
> _[bazel/google_cloud_cpp_bigquery_deps.bzl, line 34 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp-bigquery/4#-LrB4HkfEiUngnUcz1Rc:-LrB4HkfEiUngnUcz1Rd:bkzrjt) ([raw file](https://github.com/googleapis/google-cloud-cpp-bigquery/blob/9e908833a956d9507af1e4ac2c70f8af03da5061/bazel/google_cloud_cpp_bigquery_deps.bzl#L34)):_
> 
> > ```python
> >             strip_prefix = "google-cloud-cpp-0.13.0",
> >             urls = [
> >                 "https://github.com/googleapis/google-cloud-cpp/archive/v0.13.0.tar.gz",
> > ```
> 
> FYI: you can probably just depend on https://github.com/googleapis/google-cloud-cpp-common/archive/v0.13.0.tar.gz
> 
> https://github.com/googleapis/google-cloud-cpp-common/releases

This must've been a carry-over from copying the Spanner set-up. I will do this in a separate PR.

**Comment by aryann** [comment]
> > Reviewed 1 of 1 files at r3.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-bigquery/4)_ status: all files reviewed, 1 unresolved discussion (waiting on @aryann)
> 
> _[bazel/google_cloud_cpp_bigquery_deps.bzl, line 34 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp-bigquery/4#-LrB4HkfEiUngnUcz1Rc:-LrEMAhQ9xk2cqtJC5hT:bb6sh2i) ([raw file](https://github.com/googleapis/google-cloud-cpp-bigquery/blob/9e908833a956d9507af1e4ac2c70f8af03da5061/bazel/google_cloud_cpp_bigquery_deps.bzl#L34)):_
> 
> Previously, aryann (Aryan Naraghi) wrote…
> Ack.
> 
> _[google/cloud/bigquery/connection_options.cc, line 28 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp-bigquery/4#-LrEMFxIEYk1_Se20jqn:-LrEMFxJ-NCjVNbsmaOm:bkfdb6h) ([raw file](https://github.com/googleapis/google-cloud-cpp-bigquery/blob/826c804ac169cd08d8de6a7ccbf0a2448e5f6cc6/google/cloud/bigquery/connection_options.cc#L28)):_
> 
> > ```c++
> > namespace internal {
> > std::string BaseUserAgentPrefix() {
> >   // TODO(aryann): Add more info here.
> > ```
> 
> nit: consider opening an issue in GitHub and reference it here, e.g., `TODO(#1234) - add more info here`.

Good idea. I'll make a pass to do this. Look out for a PR.

**Pull request merged**
